### ISSUE TITLE
Cursor modes

### ISSUE THREAD

**Issue by PaliwalSparsh** [PaliwalSparsh/Form-A11y#4]
There will be two modes for the cursor - 
1. Create mode - In this mode, the user would be able to only create annotation boxes.
2. Move and operate mode - Here, users would be able to select one or multiple boxes, move them around, change their properties, and more.

**Comment by PaliwalSparsh** [comment]
@joshuaharry can you please review this so that I can close this issue.

**Comment by joshuaharry** [comment]
@PaliwalSparsh No worries! I've pulled your code and looked at the most recent changes.

When I run the code locally, I'm unable to move the annotation boxes around when I switch between the two mode buttons at the bottom of the screen. I also don't see code to add that functionality in the pull request. Is that behavior required to close the issue?

I'm planning to leave more detailed comments on the two commits with changes; overall, nice work. You're using the context API correctly.

What do you think about putting new functionality on feature branches and merging those into a `main` branch? I'm comfortable leaving comments on each commit, but it might be a little easier to review the code if I can look at all the diffs merged together rather than each one individually.

**Comment by PaliwalSparsh** [comment]
[e3d65b1](https://github.com/PaliwalSparsh/Form-A11y/commit/e3d65b1d7c98165e92f4080890d07caf2ff4f6e6) solves this!
